remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: Yiyang
description: The page of Yiyang Zhang's STATS201 Introduction to Machine Learning for Social Science Problem Set 1
